name: create artifacts
on: [push, workflow_dispatch]
jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install

      - name: Test with different seeds
        run: |
          echo "Testing with no seed..."
          bun run random-number-generator.js
          echo ""

          echo "Testing with string seed..."
          bun run random-number-generator.js "test-seed"
          echo ""

          echo "Testing with numeric seed..."
          bun run random-number-generator.js 1906
          echo "Generated report:"
          cat report.txt

  build:
    name: Build Executables
    runs-on: ubuntu-latest
    needs: test     


  test-linux:
    name: Test Linux Executable
    runs-on: ubuntu-latest
    needs: build